version: "3.9"

services:
  mongodb:
    image: mongo:4.4.18
    volumes:
      - mongodata:/data/db
    networks:
      - mynetwork
    restart: unless-stopped
volumes:
  mongodata:
networks:
  mynetwork:
