version: "3.9"

services:
  mongodb:
    image: mongo:4.4.18
    container_name: "mongodb"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./dockervolume/mongodb:/data/db

  commandline:
    image: pscli-img
    volumes:
      - temp:/App/temp
    depends_on:
      - mongodb

volumes:
  temp:
    driver: local
    driver_opts:
      type: none
      device: "./temp"
      o: bind
