version: "3.9"

services:
  mongodb:
    image: mongo:4.4.18
    container_name: "mongodb"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  pscli:
    image: pscli-img
    container_name: pscli
    stdin_open: true # -i
    tty: true # -t
    volumes:
      - temp:/App/temp
    depends_on:
      - mongodb
    command: info

volumes:
  temp:
    driver: local
    driver_opts:
      type: none
      device: "./temp"
      o: bind
  mongodata:
